import { defineStore } from "pinia";

export const useFormationStore = defineStore('formationStore', {
    state: () => ({
        formations: [
            { 
                id: 1, 
                category: "Informatique",
                themes: [
                    {id_theme: 1, name_theme: "Formation base de données oracle 11G"},
                    {id_theme: 2, name_theme: "La programmation orientée objet : Le langage Java"},
                    {id_theme: 3, name_theme: "Système d'exploitation : Administration Red Hat I"},
                    {id_theme: 4, name_theme: "Administration Red Hat II"},
                    {id_theme: 5, name_theme: "Linux"},
                    {id_theme: 6, name_theme: "Développement Web : Framework Laravel"},
                    {id_theme: 7, name_theme: "Framework Vue3"},
                    {id_theme: 8, name_theme: "Framework React"},
                    {id_theme: 9, name_theme: "Inertia.js"},
                    {id_theme: 10, name_theme: "CCNA v7 "},
                    {id_theme: 11, name_theme: "Cybersecurity (ISO 27032)"},
                    {id_theme: 12, name_theme: "Gestion des risques de sécurité (ISO 27005)"},
                    {id_theme: 13, name_theme: "Formation sécurité infrastructure et système"},
                    {id_theme: 14, name_theme: "Formation Infrastructures réseaux"},
                    {id_theme: 15, name_theme: "Formation systèmes & virtualisation"},
                    {id_theme: 16, name_theme: "Formation Windows Serveur 2019"},
                    {id_theme: 17, name_theme: "Développement web"},
                    {id_theme: 18, name_theme: "Formation base de données MYSQL Administration Avancée"},
                    {id_theme: 19, name_theme: "MS Project"},
                    {id_theme: 20, name_theme: "MS Access"},
                    {id_theme: 21, name_theme: "Excel – niveau intermédiaire"},
                    {id_theme: 22, name_theme: "Power BI – niveau initial"},
                    {id_theme: 23, name_theme: "Power BI – niveau intermédiaire"},
                    {id_theme: 24, name_theme: "Gestion de projet informatique"},
                    {id_theme: 25, name_theme: "ITIL &helpdesk (niveau 2)"},
                ]
            },
            { 
                id: 2, 
                category: "Communication",
                themes: [
                    {id_theme: 1, name_theme: "La communication commerciale"},
                    {id_theme: 2, name_theme: "Développer sa performance de communication"},
                    {id_theme: 3, name_theme: "Communication interpersonnelle"},
                ]
            },
            { 
                id: 3, 
                category: "Commerce et Marketing",
                themes: [
                    {id_theme: 1, name_theme: "La mise en place d’un plan d’actions commerciales et les tableaux de bord"},
                    {id_theme: 2, name_theme: "Marketing digital"},
                    {id_theme: 3, name_theme: "Développer la satisfaction client au quotidien"},
                    {id_theme: 4, name_theme: "Du plan marketing au plan d'action commercial"},
                    {id_theme: 5, name_theme: "Etude de marché et veille marketing"},
                    {id_theme: 6, name_theme: "Force de Vente"},
                    {id_theme: 7, name_theme: "Gérer son portefeuille client"},
                    {id_theme: 8, name_theme: "L'écoute client et la mesure de satisfaction"},
                    {id_theme: 10, name_theme: "La négociation dans le contrat d'affaires"},
                    {id_theme: 11, name_theme: "La vente efficace"},
                    {id_theme: 12, name_theme: "Le Coaching commercial"},
                    {id_theme: 13, name_theme: "Marketing Fondamental"},
                    {id_theme: 14, name_theme: "Négociation Commerciale"},
                    {id_theme: 15, name_theme: "Négociation de contrat à l'Internationale"},
                    {id_theme: 16, name_theme: "Prospecter-Communiquer-Convaincre"},
                    {id_theme: 17, name_theme: "Technique de vente"},
                    {id_theme: 18, name_theme: "Techniques de fidélisation Clientèle"},
                    {id_theme: 19, name_theme: "Techniques de ventes approfondies"},
                    {id_theme: 20, name_theme: "Techniques de ventes et suivi des performances"},
                    {id_theme: 21, name_theme: "Techniques du commerce international"},
                    {id_theme: 22, name_theme: "Vendre par téléphone"},
                ]
            },
            { 
                id: 4, 
                category: "Management de la qualité",
                themes: [
                    {id_theme: 1, name_theme: "Système de management de la qualité selon ISO 9001 v2015"},
                    {id_theme: 2, name_theme: "Système de management environnemental SME selon ISO 14001 v2015"},
                    {id_theme: 3, name_theme: "Audit interne selon ISO 19011 v2018"},
                    {id_theme: 4, name_theme: "Management de la sécurité des denrées alimentaires ISO 22000 v2018"},
                    {id_theme: 5, name_theme: "Management des organismes d'éducation/formation ISO 21001 v2018"},
                    {id_theme: 6, name_theme: "Management des Processus"},
                    {id_theme: 7, name_theme: "Animateur qualité"},
                    {id_theme: 8, name_theme: "Les outils de la qualité"},
                    {id_theme: 10, name_theme: "HACCP – initiation"},
                    {id_theme: 11, name_theme: "Accompagnement mise en place d’un système HACCP - Industrie alimentaire & restauration"},
                    {id_theme: 12, name_theme: "Les Bonnes pratiques d'hygiène (BPH) Industrie alimentaire & restauration"},
                    {id_theme: 13, name_theme: "Accompagnement mise en place un SMQ ISO 9001 v2015 Secteur de la santé"},
                    {id_theme: 14, name_theme: "Hygiène et sécurité en restauration"},
                ]
            },
            { 
                id: 5, 
                category: "Management",
                themes: [
                    {id_theme: 1, name_theme: "Les bases du management"},
                    {id_theme: 2, name_theme: "Le management des hommes"},
                    {id_theme: 3, name_theme: "La gestion du temps et du stress"},
                    {id_theme: 4, name_theme: "Le management de projets"},
                    {id_theme: 5, name_theme: "Construire un projet Informatique"},
                    {id_theme: 6, name_theme: "Manager une équipe projet"},
                    {id_theme: 7, name_theme: "Animer & piloter une équipe"},
                    {id_theme: 8, name_theme: "Fixer des objectifs"},
                    {id_theme: 10, name_theme: "Prendre la parole en public"},
                    {id_theme: 11, name_theme: "Tenir une réunion"},
                    {id_theme: 12, name_theme: "Fixer les objectifs et évaluer les performances"},
                    {id_theme: 13, name_theme: "Business plan"},
                    {id_theme: 14, name_theme: "Leadership"},
                    {id_theme: 15, name_theme: "Le coaching"},
                    {id_theme: 16, name_theme: "Gestion des conflits en posture de leader"},
                    {id_theme: 17, name_theme: "Conduite de projet avec PRIMAVERA"},
                    {id_theme: 18, name_theme: "Fédérer et manager son équipe"},
                    {id_theme: 19, name_theme: "La maitrise des couts"},
                    {id_theme: 20, name_theme: "Affirmation de soi"},
                    {id_theme: 21, name_theme: "Gestion de projet"},
                    {id_theme: 22, name_theme: "Gestion des risques"},
                    {id_theme: 23, name_theme: "Gestion de stocks"},
                    {id_theme: 24, name_theme: "L’assistanat"},
                    {id_theme: 25, name_theme: "Management des processus"},
                    {id_theme: 26, name_theme: "SCRUM AGILE"},
                ]
            },
            { 
                id: 6, 
                category: "Comptabilité & Finances",
                themes: [
                    {id_theme: 1, name_theme: "Audit financier et contrôle interne"},
                    {id_theme: 2, name_theme: "Audit interne"},
                    {id_theme: 3, name_theme: "Audit Interne Opérationnelle des comptes"},
                    {id_theme: 4, name_theme: "Clôture des comptes sous SCF"},
                    {id_theme: 5, name_theme: "Code des marchés publics"},
                    {id_theme: 6, name_theme: "Comptabilité analytique d'exploitation"},
                    {id_theme: 7, name_theme: "Consolidation des comptes"},
                    {id_theme: 8, name_theme: "Contrôle de gestion"},
                    {id_theme: 10, name_theme: "Elaborer et suivre son budget"},
                    {id_theme: 11, name_theme: "Etude des prix de la soumission"},
                    {id_theme: 12, name_theme: "Finances pour non financiers"},
                    {id_theme: 13, name_theme: "Fiscalité applicable aux entreprises"},
                    {id_theme: 14, name_theme: "Gestion de la trésorerie"},
                    {id_theme: 15, name_theme: "Initiation à la comptabilité"},
                    {id_theme: 16, name_theme: "L'essentiel de la Finance"},
                    {id_theme: 17, name_theme: "Lecture et Interprétation des Etats Financiers"},
                    {id_theme: 18, name_theme: "Normes Internationales IAS/IFRS"},
                    {id_theme: 19, name_theme: "Liasse fiscale"},
                    {id_theme: 20, name_theme: "Loi de finance"},
                    {id_theme: 21, name_theme: "Perfectionnement en comptabilité"},
                    {id_theme: 22, name_theme: "Procédures de dédouanement"},
                    {id_theme: 23, name_theme: "Programme d'Analyse Financière et Gestion de la Trésorerie"},
                    {id_theme: 24, name_theme: "Programme de Gestion des Appros et des Stocks"},
                    {id_theme: 25, name_theme: "Programme des Inventaires de Fin d'Exercice"},
                    {id_theme: 26, name_theme: "Recouvrement des créances"},
                    {id_theme: 27, name_theme: "Rédaction des cahiers de charge"},
                    {id_theme: 28, name_theme: "Rédaction des contrats"},
                    {id_theme: 29, name_theme: "Régime Fiscal applicable aux Entreprises"},
                    {id_theme: 30, name_theme: "Tableau de bord de Gestion"},
                    {id_theme: 31, name_theme: "Techniques douanières"},
                    {id_theme: 32, name_theme: "Tenue des stocks et inventaires"},
                ]
            },
            { 
                id: 7, 
                category: "Gestion de la Ressource Humaine",
                themes: [
                    {id_theme: 1, name_theme: "La taxe de la formation continue et professionnelle"},
                    {id_theme: 2, name_theme: "La sécurité sociale"},
                    {id_theme: 3, name_theme: "Réussir son entretien d'évaluation"},
                    {id_theme: 4, name_theme: "Le contrôle de gestion RH & système du reporting"},
                    {id_theme: 5, name_theme: "Tableau de bord de la GRH"},
                    {id_theme: 6, name_theme: "Introduction au code du travail Algérien"},
                    {id_theme: 7, name_theme: "La fonction Ressources Humaines"},
                    {id_theme: 8, name_theme: "La Gestion des carrières"},
                    {id_theme: 10, name_theme: "Atelier fiche de poste"},
                    {id_theme: 11, name_theme: "La réglementation et la gestion des contrats de travail"},
                    {id_theme: 12, name_theme: "Le métier d'assistante"},
                    {id_theme: 13, name_theme: "La gestion de la rémunération et calcul de la paie"},
                    {id_theme: 14, name_theme: "Droit de travail"},
                    {id_theme: 15, name_theme: "Les outils et mécanismes de motivation"},
                    {id_theme: 16, name_theme: "Conduire un entretien de recrutement"},
                    {id_theme: 17, name_theme: "Accueil physique et téléphonique"},
                    {id_theme: 18, name_theme: "Pratique de la paie"},
                    {id_theme: 19, name_theme: "La gestion des oeuvres sociales"},
                    {id_theme: 20, name_theme: "Elaboration d'un système d'évaluation de la formation"},
                    {id_theme: 21, name_theme: "Outils d'évaluation des actions de formations"},
                    {id_theme: 22, name_theme: "Le plan de formation"},
                    {id_theme: 23, name_theme: "Formation des formateurs"},
                ]
            },
            { 
                id: 8, 
                category: "Appro & gestion des stocks",
                themes: [
                    {id_theme: 1, name_theme: "Gestion des stocks et approvisionnement"},
                    {id_theme: 2, name_theme: "Négociation achats"},
                    {id_theme: 3, name_theme: "Gestion des achats (niveau 1)"},
                    {id_theme: 4, name_theme: "Gestion des achats pour Manager (niveau II)"},
                    {id_theme: 5, name_theme: "Tenue des stocks et inventaires en magasins et entrepôts"},
                ]
            },
            { 
                id: 9, 
                category: "Logistique",
                themes: [
                    {id_theme: 1, name_theme: "Tableau de Bord logistique"},
                    {id_theme: 2, name_theme: "Logistique export"},
                    {id_theme: 3, name_theme: "Le transport international"},
                ]
            },
            { 
                id: 10, 
                category: "HSE",
                themes: [
                    {id_theme: 1, name_theme: "LOTO (Maitrise des énergies)"},
                    {id_theme: 2, name_theme: "ATEX N°0 (électrique)"},
                    {id_theme: 3, name_theme: "ATEX N°1 (électrique)"},
                    {id_theme: 4, name_theme: "Habilitation Chimique"},
                    {id_theme: 5, name_theme: "Espace confiné"},
                    {id_theme: 6, name_theme: "Les détecteurs de gaz"},
                    {id_theme: 7, name_theme: "Habilitation électrique"},
                    {id_theme: 8, name_theme: "Evaluation des risques aux postes de travail (EvRP)"},
                    {id_theme: 10, name_theme: "Système permis de travail"},
                    {id_theme: 11, name_theme: "Méthode d’investigation des accidents & incident"},
                    {id_theme: 12, name_theme: "L’utilisation des Equipements de protection individuel (EPI)"},
                    {id_theme: 13, name_theme: "Les effets personnels de sécurité"},
                    {id_theme: 14, name_theme: "Sensibilisation aux problèmes de santé et de sécurité au travail"},
                    {id_theme: 15, name_theme: "Analyse de sécurité de travail (JSA)"},
                    {id_theme: 16, name_theme: "Gestion des risques"},
                    {id_theme: 17, name_theme: "Méthodologie de la gestion des risques et analyse"},
                    {id_theme: 18, name_theme: "Identification et analyse des risques"},
                    {id_theme: 19, name_theme: "Sécurité générale & systèmes de management HSE"},
                    {id_theme: 20, name_theme: "Identifier et réduire les risques opérationnels"},
                    {id_theme: 21, name_theme: "Identification des dangers et analyse des risques"},
                    {id_theme: 22, name_theme: "Rédaction des cahiers de charges équipements"},
                    {id_theme: 23, name_theme: "Prévention de chute d’objets"},
                    {id_theme: 24, name_theme: "Les fondamentaux en hygiène et sécurité"},
                    {id_theme: 25, name_theme: "Risques Incendie - Feu"},
                    {id_theme: 26, name_theme: "Risque industriels et chimiques"},
                    {id_theme: 27, name_theme: "Risques environnementaux"},
                    {id_theme: 28, name_theme: "Risques professionnels pour l'homme au travail"},
                    {id_theme: 29, name_theme: "Risques incendie & explosion et registres de sécurité"},
                    {id_theme: 30, name_theme: "Risques incendie dans des établissements recevant du public"},
                    {id_theme: 31, name_theme: "Lutte contre incendie"},
                    {id_theme: 32, name_theme: "Identifier et réduire les risques incendie"},
                    {id_theme: 33, name_theme: "Appliquer les consignes et plan de sécurité incendie"},
                    {id_theme: 34, name_theme: "Identifier et prévenir les incendies d'origine électrique"},
                    {id_theme: 35, name_theme: "Conduite à tenir devant une explosion"},
                    {id_theme: 36, name_theme: "Hygiène & Sécurité Industrielle"},
                    {id_theme: 37, name_theme: "Tenue des documents H&S"},
                    {id_theme: 38, name_theme: "Sureté malveillance"},
                    {id_theme: 39, name_theme: "Identifier et réduire les risques de malveillance"},
                    {id_theme: 40, name_theme: "La sureté & malveillance en entreprise"},
                    {id_theme: 41, name_theme: "Formation aux premiers secours"},
                    {id_theme: 42, name_theme: "Gestion du stress en entreprise"},
                    {id_theme: 43, name_theme: "Hygiène prévention secourisme"},
                    {id_theme: 44, name_theme: "Répondre aux exigences hygiène et sécurité dans une PME"},
                    {id_theme: 45, name_theme: "Savoir Communiquer en cas de crise QSE"},
                    {id_theme: 46, name_theme: "Hygiène et sécurité pour le personnel d'étage"},
                    {id_theme: 47, name_theme: "HACCP (restauration collective)"},
                    {id_theme: 48, name_theme: "Opérateur en vidéo surveillance"},
                    {id_theme: 49, name_theme: "Agent d'accueil, de prévention et de sureté"},
                ]
            },
            { 
                id: 11, 
                category: "Maritime et Portuaire",
                themes: [
                    {id_theme: 1, name_theme: "Le commerce international"},
                    {id_theme: 2, name_theme: "Contrat de transport maritime"},
                    {id_theme: 3, name_theme: "Le shipping management"},
                    {id_theme: 4, name_theme: "L’organisation du transport international de marchandise"},
                    {id_theme: 5, name_theme: "Les auxiliaires du transport maritime"},
                    {id_theme: 6, name_theme: "Logistique du commerce international"},
                    {id_theme: 7, name_theme: "Maitrise des incoterms 2020 dans la logistique internationale"},
                    {id_theme: 8, name_theme: "La gestion des comptes d’escale des navires"},
                    {id_theme: 10, name_theme: "Les procédures de dédouanement"},
                    {id_theme: 11, name_theme: "Les affrètements maritimes"},
                    {id_theme: 12, name_theme: "L’empotage des conteneurs"},
                    {id_theme: 13, name_theme: "La gestion des terminaux à conteneurs"},
                    {id_theme: 14, name_theme: "Les codes ISM/ISPS/MLC"},
                    {id_theme: 15, name_theme: "Le transport maritime des marchandises dangereuses \"MD\" et leur transit dans la zone portuaire (étude des dispositions du code IMDG)"},
                    {id_theme: 16, name_theme: "DRAFT-SURVEY"},
                    {id_theme: 17, name_theme: "La règlementation maritime internationale"},
                    {id_theme: 18, name_theme: "Prévention de la pollution marine"},
                    {id_theme: 19, name_theme: "Le droit maritime"},
                    {id_theme: 20, name_theme: "Désensablement des ports"},
                    {id_theme: 21, name_theme: "Gestion des opérations import/export"},
                    {id_theme: 22, name_theme: "La veille météorologie et l’impact de ses prévisions sur sécurité nautique"},
                    {id_theme: 23, name_theme: "Développement stratégique pour un nouveau port"},
                    {id_theme: 24, name_theme: "Impact du système d’information sur les rendements opérationnels"},
                    {id_theme: 25, name_theme: "La lecture et l’exploitation des certificats de classe et statutaires des navires"},
                    {id_theme: 26, name_theme: "La maitrise de la veille règlementaire"},
                    {id_theme: 27, name_theme: "Réglementation régissant les émissions"},
                    {id_theme: 28, name_theme: "Les techniques de manutention unifiée"},
                    {id_theme: 29, name_theme: "Planification et suivi des opérations portuaires"},
                    {id_theme: 30, name_theme: "Conduite en sécurité des engins de manutention et le levage"},
                    {id_theme: 31, name_theme: "Connaissement maritime (BILL OF LADING) document de transport"},
                    {id_theme: 32, name_theme: "Transit et déclaration en douanes"},
                    {id_theme: 33, name_theme: "Le transport maritime en lignes régulières et transport en tramping"},
                    {id_theme: 34, name_theme: "Maitrise des incoterms 2020 dans la logistique internationale"},
                ]
            },
            { 
                id: 12, 
                category: "Banques et assurances",
                themes: [
                    {id_theme: 1, name_theme: "Introduction aux services financiers numériques"},
                    {id_theme: 2, name_theme: "La transformation numérique des entreprises"},
                    {id_theme: 3, name_theme: "Digital business development"},
                    {id_theme: 4, name_theme: "Gestion de la fraude"},
                    {id_theme: 5, name_theme: "Comprendre les schèmes internationaux"},
                ]
            },
            { 
                id: 13, 
                category: "Industrie pharmaceutique",
                themes: [
                    {id_theme: 1, name_theme: "Validation des méthodes analytiques en industries pharmaceutiques ICH Q2"},
                    {id_theme: 2, name_theme: "Les bonnes pratiques Laboratoire de Contrôle Qualité BPL et les bonnes pratiques de fabrication BPF"},
                    {id_theme: 3, name_theme: "Les bonnes pratiques de prélèvement et d’échantillonnage en industrie pharmaceutique"},
                    {id_theme: 4, name_theme: "Études de stabilité : aspects règlementaires et pratique"},
                    {id_theme: 5, name_theme: "Rédaction du dossier technique pour l'enregistrement d'un nouveau produit"},
                    {id_theme: 6, name_theme: "Tests physico-chimiques pour l'analyse du produit fin"},
                    {id_theme: 7, name_theme: "Analyse par spectroscopie des médicaments HPLC"},
                ]
            },
            { 
                id: 14, 
                category: "Anglais des affaires",
                themes: [
                    {id_theme: 1, name_theme: "Socialiser"},
                    {id_theme: 2, name_theme: "La présentation : préparation & structure"},
                    {id_theme: 3, name_theme: "La négociation"},
                    {id_theme: 4, name_theme: "Réussir l’appel téléphonique"},
                    {id_theme: 5, name_theme: "Les écrits professionnels : e-mails & rapports"},
                ]
            },
            { 
                id: 15, 
                category: "Français des affaires",
                themes: [
                    {id_theme: 1, name_theme: "Rappel des notions de base selon le cadre européen commun de référence pour les langues (CECRL)"},
                    {id_theme: 2, name_theme: "Communication interpersonnelle en entreprise"},
                    {id_theme: 3, name_theme: "Les écrits professionnels : e-mails & rapports"},
                    {id_theme: 4, name_theme: "La présentation : préparation & structure"},
                ]
            },
            { 
                id: 16, 
                category: "Hôtellerie Tourisme",
                themes: [
                    {id_theme: 1, name_theme: "Restaurant"},
                    {id_theme: 2, name_theme: "Cuisine de collectivités"},
                    {id_theme: 3, name_theme: "Cuisine gastronomique"},
                    {id_theme: 4, name_theme: "Pâtisserie"},
                    {id_theme: 5, name_theme: "Boulangerie viennoiserie"},
                    {id_theme: 6, name_theme: "Viennoiserie"},
                    {id_theme: 7, name_theme: "Boucher hôtelier"},
                    {id_theme: 8, name_theme: "Réception & accueil"},
                    {id_theme: 10, name_theme: "Réception & Accueil hôtelier"},
                    {id_theme: 11, name_theme: "Nettoyage des chambres"},
                    {id_theme: 12, name_theme: "Agence de voyage"},
                    {id_theme: 13, name_theme: "Administration hôtelière"},
                    {id_theme: 14, name_theme: "Production et commercialisation"},
                    {id_theme: 15, name_theme: "Guide de tourisme"},
                    {id_theme: 16, name_theme: "Maîtrise des coûts en restauration"},
                    {id_theme: 17, name_theme: "Hygiène de production en cuisine"},
                ]
            },
            /* { 
                id: 17, 
                category: "Bâtiments et Travaux Publics",
                themes: [
                    {id_theme: 1, name_theme: "Voirie & Réseaux Divers"},
                    {id_theme: 2, name_theme: "Réalisation du ferraillage"},
                    {id_theme: 3, name_theme: "Installation panneaux solaires photovoltaïques et thermiques"},
                    {id_theme: 4, name_theme: "Réalisation des coffrages"},
                    {id_theme: 5, name_theme: "Topographie"},
                    {id_theme: 6, name_theme: "Installation sanitaire et gaz"},
                    {id_theme: 7, name_theme: "Peinture vitrerie"},
                    {id_theme: 8, name_theme: "Etanchéité"},
                    {id_theme: 10, name_theme: "Plâtrerie Plaquiste"},
                    {id_theme: 11, name_theme: "Charpente en bois et couverture"},
                    {id_theme: 12, name_theme: "Métreur tout corps d’état"},
                    {id_theme: 13, name_theme: "Métreur vérificateur"},
                ]
            }, */
            { 
                id: 17, 
                category: "Pêche et aquaculture",
                themes: [
                    {id_theme: 1, name_theme: "Agent en pisciculture"},
                    {id_theme: 2, name_theme: "Marin pêcheur"},
                    {id_theme: 3, name_theme: "Ramendeur"},
                    {id_theme: 4, name_theme: "Agent aquacole"},
                ]
            },
            { 
                id: 18, 
                category: "Electricité et Electronique",
                themes: [
                    {id_theme: 1, name_theme: "Opérateur de Câblage"},
                    {id_theme: 2, name_theme: "Installation & Maintenance d'un réseau Local"},
                    {id_theme: 3, name_theme: "Installateur réseau Télécommunication"},
                    {id_theme: 4, name_theme: "Electricité Industrielle"},
                    {id_theme: 5, name_theme: "Réparation des téléphones fixes et mobiles"},
                    {id_theme: 6, name_theme: "Maintenance des ascenseurs"},
                    {id_theme: 7, name_theme: "Maintenance des Systèmes automatisés"},
                    {id_theme: 8, name_theme: "Formation Fibre Optique"},
                    {id_theme: 10, name_theme: "Formation Camera et Alarmes"},
                    {id_theme: 11, name_theme: "Climatisation centrale"},
                    {id_theme: 12, name_theme: "Installation, configuration et dépannage des nouveaux systèmes de vidéosurveillance"},
                    {id_theme: 13, name_theme: "Comptage électronique haut tension de l'énergie électrique"},
                ]
            },
        ]
    })
})